export const fruits = [
  "Apple", "Banana", "Orange", "Mango", "Pineapple", "Grapes", "Strawberry",
  "Watermelon", "Peach", "Cherry", "Pear", "Plum", "Apricot", "Kiwi", "Blueberry",
  "Raspberry", "Blackberry", "Cranberry", "Lemon", "Lime", "Grapefruit",
  "Mandarin", "Tangerine", "Papaya", "Guava", "Passion Fruit", "Lychee",
  "Dragon Fruit", "Durian", "Jackfruit", "Rambutan", "Mangosteen", "Starfruit",
  "Pomegranate", "Fig", "Date", "Persimmon", "Kiwano (Horned Melon)",
  "Cherimoya (Custard Apple)", "Soursop", "Breadfruit", "Longan", "Salak (Snake Fruit)",
  "Jujube (Chinese Date)", "Loquat", "Atemoya", "Feijoa (Pineapple Guava)",
  "Ackee", "Hala Fruit", "Miracle Fruit", "Tamarind", "Brazil Nut Fruit",
  "Cempedak", "Langsat", "Pulasan", "Pomelo", "Ugli Fruit", "Breadnut",
  "Baobab Fruit", "Ambarella (Spondias dulcis)", "Ice Cream Bean",
  "Cupuacu", "Jabuticaba", "Nance", "Boysenberry", "Cloudberry",
  "Goji Berry", "Elderberry", "Mulberry", "Sea Buckthorn", "Yuzu",
  "Kumquat", "Quince", "Medlar", "Buddha’s Hand", "Santol", "Tangelo",
  "Cactus Pear", "Barberry", "Bilberry", "Loquats", "Ackee", "Monstera (Swiss Cheese Plant fruit)",
  "Chayote (technically a fruit)", "Tayberry", "Uva Ursi (Bearberry)",
  "Lingonberry", "Crowberry", "Salmonberry", "Maqui Berry", "Physalis (Cape Gooseberry)",
  "Pawpaw", "Serviceberry (Saskatoon berry)", "Chokecherry", "Huckleberry",
  "Barbadine (Giant Granadilla)", "Santol", "Sorbus (Mountain Ash berry)",
  "Rambai", "Japanese Persimmon", "Buddha’s Hand", "Santol", "Che (Thai berry)",
  "Chokeberry (Aronia)", "Fe'i Banana", "Ice Apple (Palm fruit)",
  "Jack-Pine Berry", "Monkey Orange"
];